import Header from "@/components/Header/Header";
import SideBar from "@/components/SideBar/SideBar";
import MyWalletCard from "@/components/WalletCards/MyWalletCard";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>VBA Crypo Signal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:flex flex-col w-full fixed top-0">
        <Header />
        <div className="w-full flex items-start justify-start">
          <SideBar />
          <div className="p-4 h-screen overflow-y-scroll w-full pb-[70px]">
            <div className="lg:p-8 pr-0 flex flex-col gap-6 justify-start items-start w-full bg-darkColor dark:bg-gray-600">
              <div className="w-full flex lg:flex-row flex-col items-start justify-between gap-4">
                <div className="w-full lg:w-[40%] bg-[#32393c33] py-6 lg:p-4 lg:h-[277px] rounded-[10px] flex items-start justify-between flex-col gap-5">
                  <MyWalletCard />
                </div>
                <div className="w-full lg:w-[60%] bg-[#32393c33] py-6 lg:p-0 lg:h-[277px] overflow-auto rounded-[10px]">
                  <DetailCard />
                </div>

              </div>
              

            </div>
          </div>
        </div>
      </main>
    </>
  );
}
